# Generated by Django 4.0.3 on 2022-03-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open state', 'open'), ('process state', 'under process'), ('closed state', 'closed')], default='open', max_length=15)),
                ('ticket_name', models.CharField(max_length=50)),
                ('ticket_description', models.TextField(max_length=200)),
            ],
        ),
    ]
