# Generated by Django 4.0.3 on 2022-03-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ticket open', 'ticket open'), ('ticket under review', 'ticket under review'), ('ticket closed', 'closed')], default='open', max_length=45),
        ),
    ]
